version: '3'

services:
  weblate:
    image: weblate/weblate
    ports:
      - "8080:8080"
    environment:
      WEBLATE_SITE_DOMAIN: localhost
      POSTGRES_HOST: db
      POSTGRES_DATABASE: weblate_postgres
      POSTGRES_USER: weblate
      POSTGRES_PASSWORD: pr0oSusA4
      REDIS: redis://cache:6379/1
    depends_on:
      - db
      - cache
  db:
    image: postgres
    environment:
      POSTGRES_DB: weblate_postgres
      POSTGRES_USER: weblate
      POSTGRES_PASSWORD: pr0oSusA4
  cache:
    image: redis
